title: Siyu Chen's Homepage
page-top-title: Siyu Chen
top-section-bg-text: Statistics \& Data Science
home-subtitle: Siyu Chen&ensp;|&ensp;陈思宇
copyright-text: '&copy; Siyu Chen 2023-2024. All Rights Reserved.'
